---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
##     Pip install working directories
###########################################

- name: Install tango-simlib
  command: sudo pip install {{software_root}}/tango-simlib -U --no-deps
  tags:
    - install
    - tango-simlib

- name: Install levpro
  command: sudo pip install {{software_root}}/levpro -U --no-deps
  tags:
    - install
    - levpro

- name: Install skabase
  command: sudo pip install {{software_root}}/levpro/skabase/core/{{item}} -U --no-deps
  with_items:
    - SKABaseDevice
    - SKAObsDevice
    - SKAMaster
  tags:
    - install
    - skabase

- name: Install genelt
  command: sudo pip install {{software_root}}/levpro/genelt -U --no-deps
  tags:
    - install
    - genelt

...
