---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Pip install working directories
###########################################

- block:
  - name: Install tango-simlib
    #command: sudo pip install {{software_root}}/tango-simlib -U --no-deps
    pip:
      name: "{{software_root}}/{{item}}"
      extra_args: -U --no-deps
    with_items:
      - tango-simlib
  become: True
  tags:
    - install-sw-tango-simlib

- block:
  - name: Install levpro
    #command: sudo pip install {{software_root}}/levpro -U --no-deps
    pip:
      name: "{{software_root}}/{{item}}"
      extra_args: -U --no-deps
    with_items:
      - levpro
  become: True
  tags:
    - install-sw-levpro

- block:
  - name: Install skabase
    #command: sudo pip install {{software_root}}/levpro/skabase/{{item}} -U --no-deps
    pip:
      name: "{{software_root}}/{{item}}"
      extra_args: -U --no-deps
    with_items:
      - levpro/skabase/SKABaseDevice
      - levpro/skabase/SKAObsDevice
      - levpro/skabase/SKAMaster
      - levpro/skabase/SKASubarray
      - levpro/skabase/SKACapability
      - levpro/skabase/SKAAlarmHandler
      - levpro/skabase/SKATelState
      - levpro/skabase/SKALogger
  become: True
  tags:
    - install-sw-skabase

- block:
  - name: Install refelt
    #command: sudo pip install {{software_root}}/levpro/refelt -U --no-deps
    pip:
      name: "{{software_root}}/{{item}}"
      extra_args: -U --no-deps
    with_items:
      - levpro/refelt
  become: True
  tags:
    - install-sw-refelt

...
