---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
##     Update working directories
###########################################

# Do we want to pull on refresh_sw ???

- name: Refresh levpro
  command: git -C {{software_root}}/levpro pull
  tags:
    - refresh-sw-levpro

...
