---

- name: Include MySQL default vars for playbook
  include_vars: default_mysql_vars.yml

- name: Specify MySQL root password before installing
  # without this, auth_socket will be used for root@localhost, and we won't be able to set the password
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
  become: true


- name: Check if MySQL is already installed.
  stat: path="{{ mysql_daemon_path }}/{{ mysql_daemon }}"
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes cache_valid_time=3600
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: "{{ mysql_packages }}"
  ignore_errors: yes
  when: mysql_packages is defined
  register: mysql_install_packages

#- name: Install MySQL
#  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
#  with_items: "{{ mysql_packages }}"
#  register: mysql_install_packages

- name: Start the MySQL service and enable to start on boot
  service: 
    name: "{{ mysql_daemon }}"
    state: started
    enabled: "{{ mysql_enabled_on_startup }}"
  when: mysql_packages is defined
  register: mysql_service_configuration

#- name: create /root/.my.cnf (from template) with password credentials
#  template: src=/etc/ansible/templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600
#  become: true

- name: Update mysql root password for all root accounts
  mysql_user: 
    name: "{{ mysql_root_user }}"
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
#    sql_log_bin: yes
    state: present
  with_items:
    #- "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 
  when: mysql_packages is defined

#- name: Copy the root credentials as .my.cnf file
#  template: src=mycnf.j2 dest=~/.my.cnf mode=0600

- name: Ensure Anonymous user(s) are not in the database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
  when: mysql_packages is defined

- name: Remove the test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
  when: mysql_packages is defined
  notify:
    - Restart MySQL

...
