---

###########################################
## PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
## Apt-get update and upgrade
###########################################

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

#- name: upgrade apt packages
#  apt:
#    upgrade=yes


#################################
# Install deb packages
#################################

- name: Install deb requirements packages
  apt: name={{item}} force=yes state=latest
  with_items:
    #- snmpd
    - aptitude
    - libffi-dev
    - build-essential
    - git-core
    - language-pack-en-base
    - libatk1.0-dev
    - libcairo2-dev
    - libevent-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libhdf5-serial-dev
    - libpng12-dev
    - libpq-dev
    - python-cairo-dev
    - python-dev
    - gfortran
    - screen
    #- subversion
    - zlib1g-dev
    - tzdata
    - ntpdate
    - liblapack-dev
    - libf2c2-dev
    - libatlas-base-dev
    - libssl0.9.8
    - man-db
    - manpages
    - ftp
    - gawk
    - telnet
    - tcpdump
    #- redis-server
  tags:
    - debs
    - deploy-box-debs


#################################
# Install tango deb packages
#################################

- name: Install tango deb requirements packages
  apt: name={{item}} force=yes state=latest
  with_items:
    - ansible
    #- subversion
    - xauth
    - libboost-python-dev
    - build-essential
    - software-properties-common
  tags:
    - tango-debs
    - deploy-box-tango-debs


#################################
# Install mysql
#################################

- name: Check if MySQL is already installed.
  stat: path="/etc/init.d/mysql"
  register: mysql_installed
  tags:
    - mysql
    - deploy-box-mysql
    - deploy-box-mysql-installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes cache_valid_time=3600
  when: mysql_installed.stat.exists == false
  tags:
    - mysql
    - deploy-box-mysql
    - deploy-box-mysql-installed

- name: Install mysql packages
  apt: "name={{ item }} state=installed"
  #ignore_errors: yes
  when: mysql_installed.stat.exists == false
  with_items:
    - software-properties-common
    - mysql-client-core-5.6
    - mysql-server-5.6
    - mysql-client-5.6
  tags:
    - mysql
    - deploy-box-mysql

- name: Install tango core packages
  #apt: name={{item}} force=yes state=latest
  raw: sudo apt-get install {{item}} -y
  with_items:
    - tango-db
    - tango-common
    - tango-starter
    - tango-test
    - tango-accesscontrol
    #- liblog4tango5v5
    #- libtango9
    #- libtango-java
    #- libtango-doc
    #- libtango-dev
    #- liblog4tango-dev
    #- liblog4tango-doc
  tags:
    - deploy-box-core


#################################
# Install core lib debs
#################################

- apt_key:
    id: 5AD0CC81421C3A8B
    keyserver: keyserver.ubuntu.com
  tags:
    - core-libs
    - deploy-box-core-libs

- apt_repository:
    repo: deb http://ppa.launchpad.net/lmc-cam-ska/tango/ubuntu trusty main
    state: present
  tags:
    - core-libs
    - deploy-box-core-libs
    - deploy-box-core

#- apt_key:
#    id: A8780D2D6B2E9D50
#    keyserver: keyserver.ubuntu.com
#  tags:
#    - core-libs
#    - deploy-box-core-libs

#- apt_repository:
#    repo: deb http://ppa.launchpad.net/lmc-cam-ska/tango/ubuntu precise main
#    state: present
#  tags:
#    - core-libs
#    - deploy-box-core-libs

- name: Install libtango core extra
  apt:
    name={{item}} force=yes state=latest
  with_items:
    - liblog4tango5v5
    - libtango9
    - libtango-java
    - libtango-doc
    - libtango-dev
    - liblog4tango-dev
    - liblog4tango-doc
  tags:
    - core-libs
    - deploy-box-core-libs
    - deploy-box-core


#################################
# Pip install tango pip packages
#################################

- name: Install tango pip packages
  raw: sudo pip install "{{item}}" -U
  with_items:
    - numpy
    - scipy
    - matplotlib
    - ipython<6.0
    - fandango
    - tango-admin
    - python-pytango
  tags:
    - deploy-box-pip


#################################
# Pip install itango separately
#################################

- name: Install itango pip packages - no-deps
  raw: sudo pip install "{{item}}" -U --no-deps
  # USe no-deps as it was trying to install IPython > 6.0
  # which is not compatible with Python 2.6/2.7
  with_items:
    - itango
  tags:
    - deploy-box-pip
    - deploy-box-itango


#################################
# Start Tango DB
#################################

- name: ensure that tangodb is running
  service: name=tango-db state=started
  tags:
    - deploy-box-start-tango

...
