---

###########################################
###     PRINT STUFF
############################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

#################################################################
## Ensure that your apt-get package index is up to update      ##
#################################################################

- block:
  - name: update apt packages
    become: yes
    apt:
      update_cache=yes
      cache_valid_time=3600
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Install the Java Development Kit package with apt-get       ##
#################################################################

- block:
  - name: Java Development Kit
    become: yes
    apt:
      pkg=default-jdk
      state=present
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Create a temporary working directory                        ##
#################################################################

- block:
  - name: Create working dir
    file:
      path=/tmp/working
      state=directory
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download apache-tomcat catalina web server into working dir ##
#################################################################

- block:
  - name: Download tomcat web server
    get_url:
      url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.9/bin/apache-tomcat-8.0.9.tar.gz
      dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Create a tomcat directory                                   ##
#################################################################

- block:
  - name: Create tomcat dir
    become: yes
    file:
      path=/opt/tomcat/
      state=directory
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Extract the archive to the tomcat directory                 ##
#################################################################

- block:
  - name: Extract web server
    become: yes
    shell:
      tar xzvf apache-tomcat-8.0.9.tar.gz -C /opt/tomcat/ --strip-components=1
      chdir=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download tango webapp file into working dir                 ##
#################################################################

- block:
  - name: Download tango webapp war file
    get_url:
      url=https://github.com/tango-controls/tango-webapp/releases/download/v0.2-rc3/TangoWebapp.war
      dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Copy tango webapp file into tomcat webapp directory         ##
#################################################################

- block:
  - name: Copy tango webapp file
    become: yes
    copy:
      remote_src=True
      src=/tmp/working/TangoWebapp.war
      dest=/opt/tomcat/webapps/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download mTango REST server                                ##
#################################################################

- block:
  - name: Download mTango REST server
    get_url:
      url=https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-0.3.jar
      dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download mTango REST server war file                        ##
#################################################################

- block:
  - name: Download mTango REST war file
    get_url:
      url=https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-0.3.zip
      dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Extract mTango REST server war file                         ##
#################################################################

- block:
  - name: Extract mTango REST war file
    become: yes
    unarchive:
      remote_src=True
      src=/tmp/working/mtangorest.server-rc4-0.3.zip
      dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Copy mTango REST server war file to tomcat                  ##
#################################################################

- block:
  - name: Copy mTango REST war file
    become: yes
    copy:
      remote_src=True
      src=/tmp/working/mtangorest.server-rc4-0.3/tango.war
      dest=/opt/tomcat/webapps/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Change tango war to executable mode                         ##
#################################################################

- block:
  - name: tango war executable mode
    become: yes
    file:
      mode=a+x
      dest=/opt/tomcat/webapps/tango.war
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Change mTango REST server to executable mode                ##
#################################################################

- block:
  - name: mTango REST server executable mode
    become: yes
    file:
      mode=a+x
      dest=/tmp/working/mtangorest.server-rc4-0.3.jar
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Move mTango REST server to /usr/lib/tango/server/           ##
#################################################################

- block:
  - name: Create tango server dir
    become: yes
    file:
      path=/usr/lib/tango/server/
      state=directory
  - name: Move mTango REST server
    become: yes
    shell:
      mv mtangorest.server-rc4-0.3.jar /usr/lib/tango/server/
      chdir=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Remove the temporary working directory                      ##
#################################################################

- block:
  - name: Clean artifact path
    file:
      path=/tmp/working/
      state=absent
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Update the bashrc file with globals                         ##
#################################################################

- block:
  - name: New string at the end of the file
    lineinfile: dest=~/.bashrc
                insertafter=EOF
                line='export CATALINA_HOME=/opt/tomcat\nexport JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Adding tomcat user                                          ##
#################################################################

- block:
  - name: Add tomcat user
    become: yes
    lineinfile: dest=/opt/tomcat/conf/tomcat-users.xml
                regexp='^</tomcat-users>'
                insertbefore='^</tomcat-users>'
                line='  <role rolename="admin-gui"/>\n  <role rolename="manager-gui"/>\n  <role rolename="mtango-rest"/>\n  <user username="tomcat" password="tomcat" roles="manager-gui,admin-gui"/>\n  <user username="kat" password="kat" roles="mtango-rest"/>\n</tomcat-users>'
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
### Register in TANGO DB                                       ##
#################################################################

- block:
  - name: Register mtango rest server
    register_element:
        elt_config_file: roles/deploy_tangobox/config_files/tango_config_db.json
    register: writable_result
  - name: Register the mtango rest server device properties
    register_device_properties:
        elt_config_file: roles/deploy_tangobox/config_files/tango_device_properties.json
    register: writable_result
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
# Generate executable to be uesed by astor (starter)           ##
#################################################################

- block:
  - name: Create bash file to be used by astor
    become: yes
    file: path=/usr/local/bin/TangRestServer state=touch
  - stat: path=/usr/local/bin/TangRestServer
    register: file_path
  - debug: msg="File exists"
    when: file_path.stat.exists == true
  - name: Write to bash file
    become: yes
    lineinfile: dest=/usr/local/bin/TangRestServer
                line='#!/bin/bash\n\nif [ -z $TANGO_HOST ]; then\n    TANGO_HOST=127.0.0.1:10000\nfi\n\necho "Using TANGO_HOST=$TANGO_HOST"\n\nINSTANCE_NAME=$1\necho "Using INSTANCE_NAME=$INSTANCE_NAME"\n\nJAVA_OPTS="-Xmx4G -Xshare:off -XX:+UseG1GC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5009"\necho "using JAVA_OPTS=$JAVA_OPTS"\n\n/usr/bin/java -jar $JAVA_OPTS -DTANGO_HOST=$TANGO_HOST /usr/lib/tango/server/mtangorest.server-rc4-0.3.jar $INSTANCE_NAME &'
  - name: Create executable to be used by astor
    become: yes
    file:
      mode=a+x
      dest=/usr/local/bin/TangRestServer
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
# Register in ASTOR                                            ##
#################################################################

- block:
  - name: Set StartDsPath
    set_starter_ds_path:
      facility_name="refelt"
      facility_config="TBD"
      starter_path="/usr/local/bin/"
    register: the_result
  tags:
    - deploy-tangobox-tango-webapp

- block:
  - name: Register refelt servers in Astor
    register_refelt:
      action="in_astor"
      facility_name="refelt"
      facility_config="TBD"
    register: the_result
  tags:
    - deploy-tangobox-tango-webapp

- block:
  - name: Register the rest server in Astor and start with Starter.
    start_element:
      element_config: roles/deploy_tangobox/config_files/tango_config_starter.json
    register: writable_result
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Start up the tomcat web server                              ##
#################################################################

- block:
  - name: Start tomcat
    become: yes
    shell:
      sh startup.sh
      remote_src=True
      chdir=/opt/tomcat/bin/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Start Tomcat and Apache at Boot Time                        ##
#################################################################

- block:
  - name: Create bash file to be used by astor
    become: yes
    file: path=/etc/init.d/tomcat state=touch
  - stat: path=/etc/init.d/tomcat
    register: file_path
  - debug: msg="File exists"
    when: file_path.stat.exists == true
  - name: Write to bash file
    become: yes
    lineinfile:
      dest=/etc/init.d/tomcat
      line='#!/bin/bash\n#\n# tomcat\n#\n# Description -     Start up the Tomcat servlet engine. \n\n# Source function library.\n. /etc/init.d/functions\n\n\nRETVAL=$?\nCATALINA_HOME="/opt/tomcat/"\ncase "$1" in\n start)\n        if [ -f $CATALINA_HOME/bin/startup.sh ];\n          then\n        echo $"Starting Tomcat"\n            /bin/su tomcat $CATALINA_HOME/bin/startup.sh\n        fi\n    ;;\n stop)\n        if n/su tomcat $CATALINA_HOME/bin/shutdown.sh\n        fi\n    ;;\n *)\n   echo $"Usage - $0 {start|[ -f $CATALINA_HOME/bin/shutdown.sh ];\n          then\n      echo $"Stopping Tomcat"\n            /bistop}"\n    exit 1\n    ;;\nesac\n\nexit $RETVAL'
      state=present
  - name: Create link to be used at start up
    become: yes
    shell:
      ln -s /etc/init.d/tomcat S71tomcat
      chdir=/etc/rc5.d
  tags:
    - deploy-tangobox-tango-webapp

...
