---
#################################################################
## Ensure that your apt-get package index is up to update      ##
#################################################################

- name: update apt packages
  become: yes
  apt:
    update_cache=yes
    cache_valid_time=3600
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Install the Java Development Kit package with apt-get       ##
#################################################################

- name: Java Development Kit
  become: yes
  apt:
    pkg=default-jdk
    state=present
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Create a temporary working directory                        ##
#################################################################

- name: Create working dir
  file:
    path=/tmp/working
    state=directory
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download apache-tomcat catalina web server into working dir ##
#################################################################

- name: Download tomcat web server
  get_url:
    url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.9/bin/apache-tomcat-8.0.9.tar.gz
    dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Create a tomcat directory                                   ##
#################################################################

- name: Create tomcat dir
  become: yes
  file:
    path=/opt/tomcat/
    state=directory
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Extract the archive to the tomcat directory                 ##
#################################################################

- name: Extract web server
  become: yes
  shell:
    tar xzvf apache-tomcat-8.0.9.tar.gz -C /opt/tomcat/ --strip-components=1
    chdir=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download tango webapp file into working dir                 ##
#################################################################

- name: Download tango webapp war file
  get_url:
    url=https://github.com/tango-controls/tango-webapp/releases/download/v0.2-rc3/TangoWebapp.war
    dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Copy tango webapp file into tomcat webapp directory         ##
#################################################################

- name: Copy tango webapp file
  become: yes
  copy:
    remote_src=True
    src=/tmp/working/TangoWebapp.war
    dest=/opt/tomcat/webapps/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download mTango REST server                                ##
#################################################################

- name: Download mTango REST server
  get_url:
    url=https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-0.3.jar
    dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Download mTango REST server war file                        ##
#################################################################

- name: Download mTango REST war file
  get_url:
    url=https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-0.3.zip
    dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Extract mTango REST server war file                         ##
#################################################################

- name: Extract mTango REST war file
  become: yes
  unarchive:
    remote_src=True
    src=/tmp/working/mtangorest.server-rc4-0.3.zip
    dest=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Copy mTango REST server war file to tomcat                  ##
#################################################################

- name: Copy mTango REST war file
  become: yes
  copy:
    remote_src=True
    src=/tmp/working/mtangorest.server-rc4-0.3/tango.war
    dest=/opt/tomcat/webapps/
tags:
  - deploy-tangobox-tango-webapp

#################################################################
## Change tango war to executable mode                         ##
#################################################################

- name: tango war executable mode
  become: yes
  file:
    mode=a+x
    dest=/opt/tomcat/webapps/tango.war
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Change mTango REST server to executable mode                ##
#################################################################

- name: mTango REST server executable mode
  become: yes
  file:
    mode=a+x
    dest=/tmp/working/mtangorest.server-rc4-0.3.jar
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Move mTango REST server to usr/local/bin                    ##
#################################################################

- name: Move mTango REST server
  become: yes
  shell:
    mv mtangorest.server-rc4-0.3.jar /usr/local/bin/
    chdir=/tmp/working/
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Remove the temporary working directory                      ##
#################################################################

- name: Clean artifact path
  file:
    path=/tmp/working/
    state=absent
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Update the bashrc file with globals                         ##
#################################################################

- name: New string at the end of the file
  lineinfile: dest=~/.bashrc
              insertafter=EOF
              line='export CATALINA_HOME=/opt/tomcat\nexport JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Adding tomcat user                                          ##
#################################################################

- name: Add tomcat user
  become: yes
  lineinfile: dest=/opt/tomcat/conf/tomcat-users.xml 
              regexp='^</tomcat-users>'
              insertbefore='^</tomcat-users>'
              line='  <role rolename="admin-gui"/>\n  <role rolename="manager-gui"/>\n  <role rolename="mtango-rest"/>\n  <user username="tomcat" password="tomcat" roles="manager-gui,admin-gui"/>\n  <user username="kat" password="kat" roles="mtango-rest"/>\n</tomcat-users>'
  tags:
    - deploy-tangobox-tango-webapp

#################################################################
## Start up the tomcat web server                              ##
#################################################################

- name: Start tomcat
  become: yes
  shell:
    sh startup.sh
    remote_src=True
    chdir=/opt/tomcat/bin/
  tags:
    - deploy-tangobox-tango-webapp
