---

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
##     Clone repos
###########################################

## levpro

- name: Check for levpro in software_root
  stat: path={{software_root}}/levpro
  register: p_levpro
  tags:
    - deploy-sw-levpro

- name: Clone levpro if dir not existing
  command: git clone https://github.com/ska-sa/levpro {{software_root}}/levpro
  when: not p_levpro.stat.exists
  tags:
    - deploy-sw-levpro

- name: Git pull levpro if dir exists
  command: git -C {{software_root}}/levpro pull
  when: p_levpro.stat.isdir is defined and p_levpro.stat.isdir
  tags:
    - deploy-sw-levpro

...
