---

- hosts: local
  gather_facts: true

  pre_tasks:

    - name: Source environment in bashrc file
      shell: "{{ item }}"
      args:
        executable: /bin/bash
      with_items:
        - source ~/.bashrc
    - shell: echo {{ ansible_env.TANGO_HOST}}
      when: "'TANGO_HOST' in ansible_env"

  roles:
  - { role: refresh_sw, tags: refresh_sw }
