---

############################################
###     TANGO CS DEFAULT VARS            ###
############################################
elt_tango_syslog_dir: /var/log/tango.log
elt_tango_syslog_forward_host: localhost
elt_tango_syslog_forward_port: 10514
elt_tango_syslog_forward_level: warn


elt_tango_hostname: localhost
elt_tango_port: 10000
elt_domain_name: gen_elt_001
elt_fqdn_prefix: "tango://{{elt_tango_hostname}}:{{elt_tango_port}}"
elt_device_family_name: elt
elt_internal_device_family_name: elt
elt_config_mode: full
spf_device_family_name: spf
rx_device_family_name: rx

# - ElementLogger
elt_logger_alias: elt_logger

# - ElementMaster
elt_master_alias: elt_master

# - EltMonitor
elt_monitor_alias: elt_monitor

# - LMCMonitor
lmc_monitor_alias: lmc_monitor

# - LMCManager
lmc_manager_alias: lmc_manager

# - AlarmHandler
elt_alarm_alias: alarm_handler

# - Alarm Handler
alarm_handler: "{{elt_fqdn_prefix}}/{{elt_domain_name}}/elt/alarms"

############################################
###     CONFIG FILES & OPTIONS           ###
############################################
# - Main config
elt_ds_dir: "{{ ansible_env.DSHLMC_DEVICE_DIR }}"
elt_config_dir: /opt/Software/SKA/DishLMC/dsh.elt-install/config
elt_config_file: elt_cfg.xml
elt_config_schema_file: elt_cfg.xsd

elt_manager_config:
  name: "elt_manager_cfg.xml"
  template: "elt_manager_cfg.j2"

elt_monitor_config:
  name: "elt_monitor_cfg.xml"
  template: "elt_monitor_cfg.j2"

element_logger_config:
  name: "element_logger_cfg.xml"
  template: "element_logger_cfg.j2"

lmc_manager_config:
  name: "lmc_manager_cfg.xml"
  template: "lmc_manager_cfg.j2"

lmc_monitor_config:
  name: "lmc_monitor_cfg.xml"
  template: "lmc_monitor_cfg.j2"

alarm_handler_config:
  name: "alarm_handler_cfg.xml"
  template: "alarm_handler_cfg.j2"

elt_config_vars:
  - "{{elt_manager_config}}"
  - "{{elt_monitor_config}}"
  - "{{element_logger_config}}"
  - "{{lmc_manager_config}}"
  - "{{lmc_monitor_config}}"
  - "{{alarm_handler_config}}"

# - Configuration options
elt_clear_servers: yes
elt_export_servers: no


#######################
#### ALARM HANDLER  ###
#######################
##================
##  PROPERTIES
##================
# - SKA properties
alarmhandler_ska_level: 2

# - General properties
alarmhandler_enable_config_from_file: "{{enable_config_from_file}}"
alarmhandler_config_file: "{{elt_config_dir}}/{{alarm_handler_config.name}}"
alarmhandler_astor_controlled: !!str true
alarmhandler_startup_level: 4

# - Dyn attr creation & management properties
alarmhandler_enable_dyn_attr_cleanup: "{{enable_dyn_attr_cleanup}}"
alarmhandler_enable_dyn_attr_randomize: !!str false
alarmhandler_dyn_attr_randomize_period: 3000
alarmhandler_enable_fwd_attr_init_polling: !!str false
alarmhandler_fwd_attr_init_poll_period: 5000
alarmhandler_enable_status_attr_update_polling: !!str false
alarmhandler_status_attr_update_poll_period: 3000

# - Logging properties
alarmhandler_enable_central_log_target: "{{enable_central_log_target}}"
alarmhandler_central_log_target: "{{central_log_target}}"
alarmhandler_central_log_level: "{{central_log_level}}"
alarmhandler_enable_element_log_target: "{{enable_element_log_target}}"
alarmhandler_element_log_target: "{{element_log_target}}"
alarmhandler_element_log_level: "{{element_log_level}}"
alarmhandler_enable_storage_log_target: "{{enable_storage_log_target}}"
alarmhandler_storage_log_target: "{{storage_log_target}}"
alarmhandler_storage_log_level: "{{storage_log_level}}"
alarmhandler_syslog_facility: "{{syslog_facility}}"
alarmhandler_syslog_host: "{{syslog_host}}"
alarmhandler_enable_logger_init_polling: "{{enable_logger_init_polling}}"
alarmhandler_logger_init_poll_period: "{{logger_init_poll_period}}"

# - Proxy properties
alarmhandler_enable_proxy_monitoring: !!str false ### This is performed by the ping dedicated thread not by polled cmd
alarmhandler_enable_proxy_status_attr_creation: !!str false
alarmhandler_enable_auto_admin_proxy_registration: !!str false
alarmhandler_proxy_monitoring_period: 5000 # ms
alarmhandler_proxy_status_attr_polling_period: 10000
alarmhandler_proxy_status_attr_periodic_event_period: 10000
alarmhandler_proxy_status_attr_archive_event_period: -1
alarmhandler_proxy_timeout: 20 # s
alarmhandler_enable_dev_proxy_init_polling: !!str false
alarmhandler_dev_proxy_init_poll_period: 10000


# - Formula attr properties
alarmhandler_enable_formula_attr_update_polling: !!str false
alarmhandler_formula_attr_update_poll_period: 5000
alarmhandler_formula_var_max_time_interval: "{{formula_var_max_time_interval}}"

# - Task management properties
alarmhandler_enable_clear_task_polling: !!str false
alarmhandler_clear_task_poll_period: 10000

# - Alarm Handler specific properties
alarmhandler_subscribe_retry_period: 30 # s
alarmhandler_stats_time_window: 60 # s

...
