---
# THIS IS SPECIFIC FOR REFELT - JUST TO GET A REFELT REGISTERED
# GENERALISATION OF CONFIG AND FOR OTHER ELEMENTS IS TBD

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Register in TANGO db
###########################################

- block:
  - name: Register RefElt servers, classes, devices
    register_element:
        elt_config_file: "{{software_root}}/levpro/ansible/inventories/refelt/config_files/config_db.json"
    register: the_result
  - name: Register RefElt device properties
    register_device_properties:
      elt_config_file: "{{software_root}}/levpro/ansible/inventories/refelt/config_files/device_properties.json"
    register: the_result
  tags:
    - register-refelt-in-tangodb

###########################################
###     Register in ASTOR
############################################
- block:
  - name: Set StartDsPath
    set_starter_ds_path:
      facility_name="refelt"
      facility_config="TBD"
      starter_path="/usr/local/bin/"
    register: the_result
  tags:
    - register-refelt-in-astor
    - register-refelt-in-astor-ds-path


- block:
  - name: Register RefElt in Astor and restart with Starter
    start_element:
      element_config: "{{software_root}}/levpro/ansible/inventories/refelt/config_files/config_starter.json"
    register: the_result
  tags:
    - register-refelt-in-astor
...
