---
# THIS IS SPECIFIC FOR REFELT - JUST TO GET A REFELT REGISTERED
# GENERALISATION OF CONFIG AND FOR OTHER ELEMENTS IS TBD

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Register in TANGO db
###########################################

#---
#- hosts: your_host
#  vars:
#    jsonVar: "{{ lookup('file', 'var.json') | from_json }}"
#  tasks:
#    - name: test loop
#      with_dict: "{{ jsonVar['queue'] }}"
#      shell: |
#        if echo "blue" | grep -q "{{ item.value.color }}" ; then
#            echo "success"
#        fi

- block:
  - name: Register RefElt servers, classes, devices
    register_element:
      elt_config_file:"{{ refelt_config_dir }}/ {{ refelt_db_json }}"
    register: writable_result
  tags:
    - register-refelt-in-tangodb
  - name: Register the Element's device properties.
    register_device_properties:
      elt_config_file:"{{ refelt_config_dir }}/ {{ refelt_device_properties_json }}"
  tags:
    -register-refelt-in-tangodb
  - name: Register the Element in Astor and start with Starter.
    start_element:
      elt_config_file:"{{ refelt_config_dir }}/ {{ refelt_starter_json }}"
...
